### ISSUE TITLE
feature-req./question

### ISSUE THREAD

**Issue by Steviey** [gogonzo/runner#87]
Is there a more elegant and robust way, to get a data frame back from runner as output, then this? I tried simplify='array' with no effect.

```
test<-runner(x=df,k=sSize,f=rollingAnal,simplify=FALSE,na_pad=TRUE)
            # View(test)
            # stop()

            sampleList  <-list()
            listIndex   <-0    
            for(i in 1:length(test)){
                myDf<-test[[i]]
                if(is.data.frame(myDf)==T){
                    if(nrow(myDf)>0){
                        listIndex<-listIndex+1
                        sampleList[[listIndex]]<-myDf
                    }
                }    
            }

            myOut<-do.call(data.table::rbindlist,list(sampleList,fill=FALSE,idcol=NULL))

```

**Comment by gogonzo** [comment]
Hi @Steviey 
unfortunately [simplify2array](https://stat.ethz.ch/R-manual/R-devel/library/base/html/lapply.html) (and thus `runner`) doesn't support the `data.frame` which could be really hard. I'll do some research to enable this with the low cost but I'm sceptical about robust solutions.

**Comment by Steviey** [comment]
Hey @gogonzo , thank you! It's funny, I tried up to 5 packages for rolling functions. None of them is able to return a simple data frame :-). Might be, a list of data frames is more appropriate. By the way, great package, great street-art!

**Comment by gogonzo** [comment]
Thanks @Steviey I appreciate your opinion 💪
I have been thinking about this `data.frame` output and decided to abandon this. It will be impossible to make a robust solution to bind `data.frame` elements of the list. It will require to check if all elements of the list are `data.frame` (or NULL) and that their common columns have the same type. Alternatively I could add `rtables::rbindlist` or `dplyr::bind_rows` but `runner` suppose to have minimal dependencies. Since user know what kind of output is produced, one can use add extra line to bind.
