### ISSUE TITLE
Q: multiple values having same idx

### ISSUE THREAD

**Issue by jangorecki** [gogonzo/runner#89]
Hi,
I am wondering what is the use case of multiple values having same idx?

**Comment by gogonzo** [comment]
Hi @jangorecki ,
example use case is when one would like to calculate 7-days running average on the data which occurs irregularly. For example transactional data, or anything else which can happen multiple times a day. I hope that's ok 👍 

```r
df <- data.frame(
  date = Sys.Date() + c(2, 3, 4, 6, 8, 8, 9, 10),
  x = rnorm(8)
)

runner(df, f = function(x) mean(x$x), idx = "date", k = "7 days")
```

**Comment by jangorecki** [comment]
I got it but I don't see a reason to analyze data which are not aggregated. Timeseries with a dups in index is not good object for consumption and I would aggregate it so index is unique. I wonder what are the use cases which cannot follow this methodology.

**Comment by gogonzo** [comment]
There are data which don't follow typical time series concept. For example sport events, or an online gaming have a different shape. There are gaps in time with no observations (individual performances), which are then followed by a multiple observations in very short time. Aggregation is not a solution if one wants to predict a single performance based on the recent performances, so when building a model we actually need all data points. Of course we can also go to more detailed timestamp, so that these indexes will actually differ - but it's not a solution worth a shot because if data is irregular algorithm need to "run" through the indices and check each one if it falls into the time window.

**Comment by jangorecki** [comment]
Thank you for elaborating on that. It well answers my question.
